source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

project 'NextGenExample'
workspace 'NextGenExampleWorkspace'

target 'NextGenExample' do
    
    use_frameworks!
    
    pod 'MBProgressHUD',            '~> 0.9.2'
    
    # NextGen
    pod 'GoogleMaps'
    pod 'UAProgressView'
    pod 'PromiseKit',               '~> 3.0'
    pod 'AlamofireImage',           '~> 2.0'
    pod 'NextGenDataManager',       :path => '../../cpe-manifest-ios-data'

end
