source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

project 'NextGenExample'
workspace 'NextGenExampleWorkspace'

target 'NextGenExample' do
    
    use_frameworks!
    
    pod 'NextGenDataManager', :path => '../../nextgen-data'
    
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'GoogleMaps'
    pod 'UAProgressView'

end
